### ISSUE TITLE
ImportError: No module named svgutils

### ISSUE THREAD

**Issue by Maverick-Shark** [bzhxx/LCD-Game-Shrinker#1]
Hi,
When I do "python shrink_it.py" I get the following error:

```
$ python shrink_it.py
Traceback (most recent call last):
  File "shrink_it.py", line 32, in <module>
    import svgutils
ImportError: No module named svgutils
```

I've installed on my Ubuntu 20.04.2 LTS:

```
$ python --version
Python 2.7.18
```

```
$ pip list | grep svgutils
svgutils               0.3.4
```        

Thanks,
Shark

**Comment by bzhxx** [comment]
Hi Shark,
you need to use python3.
let me know if you can run it without error.
bzhxx

**Comment by Maverick-Shark** [comment]
Hi,
I've python3 installed too:

```
$ python3 --version
Python 3.8.10
```

Thanks for your help,
Shark

**Comment by bzhxx** [comment]
Have you solved it ?
Did you mix different python version ?
You can try:
Python3 shrink_it.py
python3.8 shrink_it.py

**Comment by Maverick-Shark** [comment]
Hi,
Not sure if I'm doing this task correctly.


```
$ python3 shrink_it.py
gnw_ball                 |--------------------| 0/1 UnzipTraceback (most recent call last):
  File "shrink_it.py", line 132, in <module>
    rom_parser.set_parameters(rom_name, rom.mame_rom_dir)
  File "/home/linux/game-and-watch/LCD-Game-Shrinker-main/rom_parser.py", line 330, in set_parameters
    tree = lxml.etree.parse(layout_file)
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1859, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1789, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 652, in lxml.etree._raiseParseError
OSError: Error reading file './build/gnw_ball/original/default.lay': failed to load external entity "./build/gnw_ball/original/default.lay"
```

I've:
`
input/rom/gnw_ball.zip with gnw_ball.svg and ac-01 files.
`
and
`
input/artwork/gnw_ball.zip with BackgroundNS.png and Unit.png files.
`


Thanks and best regards,
Shark

**Comment by bzhxx** [comment]
You also need default.lay in input/artwork/gnw_ball.zip

**Comment by Maverick-Shark** [comment]
Thanks!! I got it!!!

Best regards,
Shark

**Comment by bzhxx** [comment]
Success ??

**Comment by Maverick-Shark** [comment]
Yes!!! Downloading complete artwork and doing python3 shrink_it.py

Thanks a lot!!!

**Comment by bzhxx** [comment]
Need to clarify how to setup this tool.
